# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True, default='', verbose_name='\u8bcd\u89e3')),
                ('examples', models.TextField(blank=True, default='', verbose_name='\u8bcd\u89e3')),
            ],
        ),
    ]
