# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='slug',
            field=models.CharField(db_index=True, default=datetime.datetime(2016, 5, 27, 11, 47, 47, 562000, tzinfo=utc), max_length=256, verbose_name='\u7f51\u5740'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='mode',
            field=models.ManyToManyField(to='learn.Mode', verbose_name='\u5f52\u5c5e\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.CharField(db_index=True, default=datetime.datetime(2016, 5, 27, 11, 48, 5, 109000, tzinfo=utc), max_length=256, verbose_name='\u7f51\u5740'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mode',
            name='description',
            field=models.TextField(default='', verbose_name='\u7b80\u4ecb'),
        ),
    ]
