# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 12:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0003_auto_20160527_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u5206\u7c7b')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='\u5206\u7c7b\u7f51\u5740')),
                ('intro', models.TextField(default='', verbose_name='\u5206\u7c7b\u7b80\u4ecb')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': '\u5355\u8bcd', 'verbose_name_plural': '\u5355\u8bcd'},
        ),
        migrations.RemoveField(
            model_name='word',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='word',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='word',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='word',
            name='name',
        ),
        migrations.AddField(
            model_name='word',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='word',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default=datetime.datetime(2016, 5, 27, 12, 13, 4, 695000, tzinfo=utc), max_length=256, verbose_name='\u5355\u8bcd'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
        migrations.AddField(
            model_name='word',
            name='column',
            field=models.ManyToManyField(to='learn.Column', verbose_name='\u5f52\u5c5e\u5206\u7c7b'),
        ),
    ]
