# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20160527_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='name',
        ),
    ]
