# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20160527_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='author',
        ),
    ]
