# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-28 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20160527_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u529f\u80fd')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='\u529f\u80fd\u7f51\u5740')),
                ('intro', models.TextField(default='', verbose_name='\u529f\u80fd\u7b80\u4ecb')),
                ('nav_display', models.BooleanField(default=True, verbose_name='\u5bfc\u822a\u663e\u793a')),
                ('home_display', models.BooleanField(default=True, verbose_name='\u9996\u9875\u663e\u793a')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u529f\u80fd',
                'verbose_name_plural': '\u529f\u80fd',
            },
        ),
        migrations.AddField(
            model_name='column',
            name='function',
            field=models.ManyToManyField(to='learn.Function', verbose_name='\u5f52\u5c5e\u529f\u80fd'),
        ),
    ]
