# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-28 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20160528_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'verbose_name': '\u5206\u7c7b', 'verbose_name_plural': '\u5206\u7c7b'},
        ),
    ]
