# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-28 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_auto_20160528_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='\u7b14\u8bb0'),
        ),
    ]
