# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-29 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_auto_20160529_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.IntegerField(default=20),
        ),
    ]
