# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_auto_20160529_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='column',
            field=models.OneToOneField(default='\u516d\u7ea7', max_length=256, on_delete=django.db.models.deletion.CASCADE, to='learn.Column'),
        ),
    ]
