# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-29 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0020_auto_20160529_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='column',
        ),
    ]
