# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0021_remove_user_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='column',
            field=models.CharField(default='\u516d\u7ea7', max_length=256),
        ),
    ]
