# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0023_user_daka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daka',
        ),
    ]
