# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0025_auto_20160530_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.CharField(max_length=256, verbose_name='\u5206\u7c7b\u7f51\u5740'),
        ),
    ]
