# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0030_auto_20160530_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_add',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='wordfor',
        ),
        migrations.AddField(
            model_name='word',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='\u7b14\u8bb0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='column',
            field=models.CharField(default='\u516d\u7ea7', max_length=256),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
