# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0034_auto_20160531_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
