# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0035_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=0, null=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
