# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0037_auto_20160531_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u7b14\u8bb0', 'verbose_name_plural': '\u7b14\u8bb0'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='word',
            new_name='wordfor',
        ),
    ]
